### ISSUE TITLE
Render errors+2 plugins in menu

### ISSUE THREAD

**Issue by astaentreri** [IlliumIv/Poe.Ninja-Pricer#1]
Plugin blinks 0 value in stash (error doesnt appear when hovering over item, only begins and stops when opening/closing stash), doesn't draw item value, draws debug window instead (when hovering), there are 2 "plugins" in hud menu, one when checked properly downloads data from poe.ninja (and chaos orb icon) and changes name to Poe.ninja Pricer, 2nd one does nothing and outputs nothing to debug

![image](https://user-images.githubusercontent.com/19862908/65531884-2c209080-defb-11e9-8f4b-f5e1bf502c33.png)
![image](https://user-images.githubusercontent.com/19862908/65531921-3773bc00-defb-11e9-9aea-8c75eed62094.png)
![image](https://user-images.githubusercontent.com/19862908/65531944-3fcbf700-defb-11e9-8e25-03ad5fc1e435.png)

**Comment by Murdoc84** [comment]
Same here, Dll from release

**Comment by elil9** [comment]
Doing it via VS is not working either. I really hope that we can use this. Trade macro is so slow :s

**Comment by astaentreri** [comment]
sithylis updated in his repo, his version works, so issue closed
